security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_ADMIN:
      - ROLE_CAN_MANAGE_INVENTORY
      - ROLE_CAN_MANAGE_ORDERS
      - ROLE_CAN_MANAGE_USERS
      - ROLE_CAN_MANAGE_WAREHOUSES
    ROLE_MANAGE_INVENTORY:
      - ROLE_CAN_MANAGE_INVENTORY
    ROLE_MANAGE_ORDERS:
      - ROLE_CAN_MANAGE_ORDERS
    ROLE_MANAGE_USERS:
      - ROLE_CAN_MANAGE_USERS
    ROLE_CAN_MANAGE_WAREHOUSES:
    - ROLE_CAN_MANAGE_WAREHOUSES
    ROLE_SUPER_ADMIN:
      - ROLE_ADMIN

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  firewalls:
    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
      logout:       true
      anonymous:    true

  access_control:
  - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/register, role: ROLE_ADMIN }
  - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/admin/, role: [ROLE_LOADER_INVENTORY,ROLE_WAREHOUSE_ADMIN,ROLE_ADMIN] }