security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_SUPER_ADMIN:
      - ROLE_ADMIN
    ROLE_INVENTORY: [ROLE_USER]
    ROLE_ADMIN:
      - ROLE_UPDATE_ORDERS
      - ROLE_MANAGE_INVENTORY
      - ROLE_MANAGE_ORDERS
      - ROLE_MANAGE_USERS
      - ROLE_MANAGE_WAREHOUSES
      - ROLE_USER
    ROLE_MANAGE_INVENTORY:
      - ROLE_CAN_EDIT_INVENTORY
      - ROLE_CAN_READ_INVENTORY
      - ROLE_CAN_DELETE_INVENTORY
      - ROLE_USER
    ROLE_MANAGE_ORDERS:
      - ROLE_CAN_CREATE_ORDERS
      - ROLE_CAN_READ_ORDERS
      - ROLE_CAN_UPDATE_ORDERS
      - ROLE_CAN_DELETE_ORDERS
      - ROLE_CAN_SYNC_ORDERS
      - ROLE_USER
    ROLE_UPDATE_ORDERS:
      - ROLE_CAN_CREATE_ORDERS
      - ROLE_CAN_READ_ORDERS
      - ROLE_CAN_UPDATE_ORDERS
    ROLE_MANAGE_USERS:
      - ROLE_CAN_CREATE_USERS
      - ROLE_CAN_READ_USERS
      - ROLE_CAN_UPDATE_USERS
      - ROLE_CAN_DELETE_USERS
      - ROLE_USER
    ROLE_MANAGE_WAREHOUSES:
      - ROLE_CAN_CREATE_WAREHOUSES
      - ROLE_CAN_READ_WAREHOUSES
      - ROLE_CAN_EDIT_WAREHOUSES
      - ROLE_CAN_DELETE_WAREHOUSES
      - ROLE_USER

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  firewalls:
    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
      logout:       true
      anonymous:    true

  access_control:
  - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/register, role: ROLE_ADMIN }
  - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/admin/, role: [ROLE_USER] }
