version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www/html:delegated
    environment:
      - VIRTUAL_HOST=inventory.local
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    command: >
      sh -c '
        /etc/init.d/nginx start && /etc/init.d/php7.2-fpm start
        composer install
        sleep 5
        composer deploy-application
        php bin/console --no-interaction doctrine:migrations:migrate
        php bin/console doctrine:schema:update --force
        bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json
        touch var/data/inventory.sqlite
        chmod 777 -R var/data/inventory.sqlite
        supervisord
      '
    container_name: inventory_web
  db:
    image: mysql:5.7
    volumes:
      - ./Docker/mysql.cnf.d/sql_mode.cnf:/etc/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "symfony"
      MYSQL_USER: "symfony"
      MYSQL_PASSWORD: "symfony"
      MYSQL_ROOT_PASSWORD: "symfony"
    depends_on:
    - web
    ports:
      - 3306:3306
    container_name: inventory_db

networks:
  default:
    external:
      name: nginx-proxy
